headers:
  all:
    request:
      - propagate:
          named: 'Authorization'
supergraph:
  introspection: true
include_subgraph_errors:
  all: true 
cors:
  origins:
    - http://localhost:3000
    - https://studio.apollographql.com